# ---------------------------------------------------------------------------------------------------------------------
#                            SPRING: Configuración general y perfiles
# ---------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: microservicio-mensajeria
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# ---------------------------------------------------------------------------------------------------------------------
#                                   DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:default}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      connect-timeout: ${SPRING_DATA_REDIS_CONNECT_TIMEOUT:5s}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:5s}
      ssl:
        enabled: true

# ---------------------------------------------------------------------------------------------------------------------
#                              DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_MENSAJERIA:jdbc:postgresql://localhost:5432/db_microservicio_mensajeria}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      initialization-fail-timeout: 120000
      pool-name: LukaHikariCP

# ---------------------------------------------------------------------------------------------------------------------
#                                   JPA: Configuración de persistencia ORM Hibernate
# ---------------------------------------------------------------------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false

# ---------------------------------------------------------------------------------------------------------------------
#                              RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    connection-name: ${spring.application.name}
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5671}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    ssl:
      enabled: ${SPRING_RABBITMQ_SSL_ENABLED:false}
      algorithm: ${SPRING_RABBITMQ_SSL_ALGORITHM:TLSv1.2}
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 3000ms
          max-attempts: 3
          multiplier: 2.0
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

# ---------------------------------------------------------------------------------------------------------------------
#                                   MAIL: Configuración del servidor de correo SMTP
# ---------------------------------------------------------------------------------------------------------------------
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${SPRING_MAIL_HOST:smtp.gmail.com}
        debug: false

# ---------------------------------------------------------------------------------------------------------------------
#                                   SERVER: Puerto y configuración de red local
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8084

# ---------------------------------------------------------------------------------------------------------------------
#                                 MANAGEMENT: Redirecciones de Actuator Health
# ---------------------------------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    rabbitmq:
      connection-name: ${spring.application.name}
      enabled: true
    db:
      enabled: true
    mail:
      enabled: false
    diskspace:
      enabled: false

# ---------------------------------------------------------------------------------------------------------------------
#                                  LOGGING: Configuración y patrón de trazas log
# ---------------------------------------------------------------------------------------------------------------------
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%X{correlationId:-NoID}] - %msg%n"
  level:
    root: INFO
    "org.springframework.web.servlet.DispatcherServlet": INFO
    "org.hibernate.SQL": WARN

# ---------------------------------------------------------------------------------------------------------------------
#                                   LUKA: Credenciales JWT de seguridad local
# ---------------------------------------------------------------------------------------------------------------------
luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY}

# ---------------------------------------------------------------------------------------------------------------------
#                                 TWILIO: Credenciales e integración del API de Twilio
# ---------------------------------------------------------------------------------------------------------------------
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  api-key-sid: ${TWILIO_API_KEY_SID}
  api-key-secret: ${TWILIO_API_KEY_SECRET}
  messaging-service-sid: ${TWILIO_MESSAGING_SERVICE_SID}
  sandbox-whatsapp-from: ${TWILIO_SANDBOX_WHATSAPP_FROM:}
  phone:
    number: ${TWILIO_SMS_FROM:}
  whatsapp:
    from: ${TWILIO_WHATSAPP_FROM:}
  api-key:
    sid: ${TWILIO_API_KEY_SID}
    secret: ${TWILIO_API_KEY_SECRET}
    use-api-key: true
  auth:
    token: ${TWILIO_AUTH_TOKEN:}
  account:
    sid: ${TWILIO_ACCOUNT_SID}

# ---------------------------------------------------------------------------------------------------------------------
#                                  EMAIL: Configuración de origen y destino de correo institucional
# ---------------------------------------------------------------------------------------------------------------------
email:
  from: ${SPRING_MAIL_USERNAME:noreply@luka.pe}
  soporte: ${EMAIL_SOPORTE:soporte@luka.pe}
  nombre:
    empresa: SAAS FINANCIERO
