# ---------------------------------------------------------------------------------------------------------------------
#                            SPRING: Configuración general, perfiles e importación de .env
# ---------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: microservicio-auditoria
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

# ---------------------------------------------------------------------------------------------------------------------
#                                   DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: true

# ---------------------------------------------------------------------------------------------------------------------
#                              DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/db_luka_auditoria
    username: postgres
    password: adminUTP
    driver-class-name: org.postgresql.Driver

# ---------------------------------------------------------------------------------------------------------------------
#                                   JPA: Configuración de persistencia ORM Hibernate
# ---------------------------------------------------------------------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# ---------------------------------------------------------------------------------------------------------------------
#                              RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    connection-name: ${spring.application.name}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    cache:
      channel:
        size: 10
        checkout-timeout: 1000
    connection-timeout: 10000
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    publisher-confirm-type: correlated
    publisher-returns: true

# ---------------------------------------------------------------------------------------------------------------------
#                                   TASK: Pool de hilos para tareas programadas
# ---------------------------------------------------------------------------------------------------------------------
  task:
    scheduling:
      pool:
        size: 2

# ---------------------------------------------------------------------------------------------------------------------
#                                   SERVER: Puerto y configuración de red local
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8082

# ---------------------------------------------------------------------------------------------------------------------
#                                 MANAGEMENT: Redirecciones de Actuator Health
# ---------------------------------------------------------------------------------------------------------------------
management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      path-mapping:
        health: health-internal

# ---------------------------------------------------------------------------------------------------------------------
#                                   LUKA: Credenciales JWT de seguridad local
# ---------------------------------------------------------------------------------------------------------------------
luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY:}

# ---------------------------------------------------------------------------------------------------------------------
#                                APPLICATION: Parámetros del token de seguridad
# ---------------------------------------------------------------------------------------------------------------------
application:
  security:
    jwt:
      expiration: 86400000

# ---------------------------------------------------------------------------------------------------------------------
#                                  AUDITORIA: Reglas de protección fuerza bruta
# ---------------------------------------------------------------------------------------------------------------------
auditoria:
  seguridad:
    max-intentos-fallidos: 3
    ventana-minutos: 10
    bloqueo-minutos: 30

# ---------------------------------------------------------------------------------------------------------------------
#                                  LOGGING: Configuración y patrón de trazas log
# ---------------------------------------------------------------------------------------------------------------------
logging:
  level:
    root: INFO
    com:
      auditoria: DEBUG
    org:
      springframework:
        security: WARN
        transaction: INFO
        amqp: WARN
        boot:
          actuate: WARN
      hibernate:
        SQL: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5p [%X{correlationId:-NoID}] - %msg%n"
  file:
    name: logs/microservicio-auditoria.log
