spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: microservicio-pago
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/db_luka_pagos}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:adminUTP}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin123@localhost:8761/eureka/}

luka:
  jwt:
    clave-secreta: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiracion-ms: 86400000

stripe:
  # Se añade ":sk_test_..." como respaldo por si no existe la variable de entorno
  api-key: ${STRIPE_SECRET_KEY:sk_test_coloca_aqui_tu_clave_si_no_usas_variable}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_mock_secret}
  success-url: ${FRONTEND_URL:http://localhost:3000}/suscripcion/exito
  cancel-url: ${FRONTEND_URL:http://localhost:3000}/suscripcion/cancelado
  
  # ============================================
# LOGGING (CONVERTIDO A FORMATO YAML)
# ============================================
logging:
  level:
    root: INFO
    com:
      pagos: DEBUG # Cambiado de com.usuario a com.pagos por ser el paquete de este servicio
    org:
      springframework:
        security: INFO
        transaction: INFO
        web: INFO
        amqp:
          rabbit: INFO
      hibernate:
        SQL: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5p - %msg%n"
