server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_luka_pagos
    username: postgres
    password: adminUTP
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      ssl:
        enabled: false

eureka:
  client:
    enabled: false
