# ---------------------------------------------------------------------------------------------------------------------
#    SERVER: Puerto y configuración de red local
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8087

# ---------------------------------------------------------------------------------------------------------------------
#    SPRING: Configuración general, perfiles e importación de .env.local
# ---------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:file:../.env.local[.properties]"

# ---------------------------------------------------------------------------------------------------------------------
#    DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_PAGOS:jdbc:postgresql://localhost:5432/db_microservicio_pago}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:adminUTP}

# ---------------------------------------------------------------------------------------------------------------------
#    RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    connection-name: ${spring.application.name}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

# ---------------------------------------------------------------------------------------------------------------------
#    DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}

# ---------------------------------------------------------------------------------------------------------------------
#    LUKA: Credenciales JWT de seguridad local
# ---------------------------------------------------------------------------------------------------------------------
luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY:}
    expiracion-ms: 86400000


# Desactivar discovery y eureka
spring:
  cloud:
    discovery:
      enabled: false

management:
  health:
    discovery:
      enabled: false
