spring.application.name=microservicio-cliente

# ============================================
# SERVIDOR
# ============================================
server.port=8084

# URL del microservicio-auditoría
auditoria.service.url=http://localhost:8082/api/v1/auditoria/registrar
# ============================================
# BASE DE DATOS
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_microservicio_cliente
spring.datasource.username=postgres
spring.datasource.password=adminUTP
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# JWT (CLAVE PARA TU SISTEMA)
# ============================================
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
# ============================================
# LOGGING (OPTIMIZADO)
# ============================================
logging.level.root=INFO

# Tu proyecto
logging.level.com.iam=DEBUG

# Seguridad
logging.level.org.springframework.security=DEBUG

# JPA
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Transacciones
logging.level.org.springframework.transaction=DEBUG

# Formato logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Archivo de logs
logging.file.name=logs/iam-service.log
logging.file.max-size=10MB
logging.file.max-history=30