# ---------------------------------------------------------------------------------------------------------------------
#    SERVER: Puerto y configuración de red local
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8085

# ---------------------------------------------------------------------------------------------------------------------
#    SPRING: Configuración general, perfiles e importación de .env.local
# ---------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:file:../.env.local[.properties]"

# ---------------------------------------------------------------------------------------------------------------------
#    DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_FINANCIERO_NAME:db_luka_financiero}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:adminUTP}

# ---------------------------------------------------------------------------------------------------------------------
#    RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

# ---------------------------------------------------------------------------------------------------------------------
#    DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: none

# ---------------------------------------------------------------------------------------------------------------------
#    LUKA: Credenciales JWT de seguridad local
# ---------------------------------------------------------------------------------------------------------------------
luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY:}
    expiracion-ms: 86400000
