# ---------------------------------------------------------------------------------------------------------------------
#    SPRING: Configuración general, perfiles e importación de .env.local
# ---------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:file:../.env.local[.properties]"

# ---------------------------------------------------------------------------------------------------------------------
#                              DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_SUSCRIPCIONES:jdbc:postgresql://localhost:5432/db_microservicio_suscripciones}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:adminUTP}

# ---------------------------------------------------------------------------------------------------------------------
#                              RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    connection-name: ${spring.application.name}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

# ---------------------------------------------------------------------------------------------------------------------
#                                   DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:default}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: true

# ---------------------------------------------------------------------------------------------------------------------
#                               MICROSERVICIO: Direcciones de conexión de servicios externos
# ---------------------------------------------------------------------------------------------------------------------
url:
  prod:
    financiero: ${URL_PROD_FINANCIERO:http://localhost:8085}
