spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: microservicio-suscripciones
  datasource:
    url: jdbc:postgresql://localhost:5432/db_luka_suscripciones
    username: postgres
    password: adminUTP
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    connection-name: ${spring.application.name}
    connection-timeout: 10000
    listener:
      simple:
        auto-startup: true
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: none

url:
  prod:
    financiero: http://localhost:8085

server:
  port: 8088

luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY:}
    expiracion-ms: 86400000

logging:
  level:
    root: INFO
    com.suscripciones: DEBUG
    org.springframework.security: WARN
    org.springframework.transaction: INFO
    org.springframework.web: INFO
    org.springframework.amqp: WARN
    org.springframework.boot.actuate: WARN
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5p - %msg%n"

management:
  endpoints:
    web:
      path-mapping:
        health: health-internal

---
# Este nuevo documento YAML se procesa DESPUÉS del import de spring.config.import,
# lo que permite sobrescribir los valores importados de .env localmente.
URL_PROD_FINANCIERO: http://localhost:8085
