# ---------------------------------------------------------------------------------------------------------------------
#                            SPRING: Configuración general, perfiles e importación de .env
# ---------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: microservicio-suscripciones
  profiles:
    active: local
  sql:
    init:
      mode: always

# ---------------------------------------------------------------------------------------------------------------------
#                              DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_SUSCRIPCIONES:jdbc:postgresql://localhost:5432/db_microservicio_suscripciones}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:adminUTP}
    driver-class-name: org.postgresql.Driver

# ---------------------------------------------------------------------------------------------------------------------
#                                   JPA: Configuración de persistencia ORM Hibernate
# ---------------------------------------------------------------------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ---------------------------------------------------------------------------------------------------------------------
#                              RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    connection-name: ${spring.application.name}
    connection-timeout: 10000
    listener:
      simple:
        auto-startup: true

# ---------------------------------------------------------------------------------------------------------------------
#                                   DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      repositories:
        enabled: false

# ---------------------------------------------------------------------------------------------------------------------
#                                  CACHE: Configuración del tipo de caché de Spring
# ---------------------------------------------------------------------------------------------------------------------
  cache:
    type: none

# ---------------------------------------------------------------------------------------------------------------------
#                                   SERVER: Puerto y configuración de red local
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8088

# ---------------------------------------------------------------------------------------------------------------------
#                                   LUKA: Credenciales JWT de seguridad local
# ---------------------------------------------------------------------------------------------------------------------
luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY:}
    expiracion-ms: 86400000

# ---------------------------------------------------------------------------------------------------------------------
#                               MICROSERVICIO: Direcciones de conexión de servicios externos
# ---------------------------------------------------------------------------------------------------------------------
url:
  prod:
    financiero: ${URL_PROD_FINANCIERO:http://localhost:8085}

# ---------------------------------------------------------------------------------------------------------------------
#                                  LOGGING: Configuración y patrón de trazas log
# ---------------------------------------------------------------------------------------------------------------------
logging:
  level:
    root: INFO
    com:
      suscripciones: DEBUG
    org:
      springframework:
        security: WARN
        transaction: INFO
        web: INFO
        amqp: WARN
        boot:
          actuate: WARN
      hibernate:
        SQL: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5p - %msg%n"

# ---------------------------------------------------------------------------------------------------------------------
#                                 MANAGEMENT: Redirecciones de Actuator Health
# ---------------------------------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      path-mapping:
        health: health-internal
