spring.application.name=microservicio-auditoria

# ============================================
# SERVIDOR
# ============================================
server.port=8082

# ============================================
# BASE DE DATOS - POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_microservicio_auditoria
spring.datasource.username=postgres
spring.datasource.password=adminUTP
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ============================================
# LOGGING (OPTIMIZADO)
# ============================================
logging.level.root=INFO

# Tu proyecto
logging.level.com.iam=DEBUG

# Seguridad
logging.level.org.springframework.security=DEBUG

# JPA
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Transacciones
logging.level.org.springframework.transaction=DEBUG

# Formato logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Archivo de logs
logging.file.name=logs/iam-service.log
logging.file.max-size=10MB
logging.file.max-history=30