server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_luka_usuario
    username: postgres
    password: adminUTP
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      ssl:
        enabled: false
      repositories:
        enabled: false
  cache:
    type: none

eureka:
  client:
    enabled: false
