# ---------------------------------------------------------------------------------------------------------------------
#                            SPRING: Configuración general, perfiles e importación de .env
# ---------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: microservicio-usuario
  profiles:
    active: local
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# ---------------------------------------------------------------------------------------------------------------------
#                                   DATA: Configuración de base de datos de Redis
# ---------------------------------------------------------------------------------------------------------------------
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:default}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: true

# ---------------------------------------------------------------------------------------------------------------------
#                              DATASOURCE: Conexión y credenciales de PostgreSQL local
# ---------------------------------------------------------------------------------------------------------------------
  datasource:
    url: ${SPRING_DATASOURCE_URL_USUARIO:jdbc:postgresql://localhost:5432/db_microservicio_usuario}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:adminUTP}
    driver-class-name: org.postgresql.Driver

# ---------------------------------------------------------------------------------------------------------------------
#                                   JPA: Configuración de persistencia ORM Hibernate
# ---------------------------------------------------------------------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# ---------------------------------------------------------------------------------------------------------------------
#                              RABBITMQ: Broker de mensajería asíncrona y topologías
# ---------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    connection-name: ${spring.application.name}
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    connection-timeout: 10000
    listener:
      simple:
        auto-startup: true

# ---------------------------------------------------------------------------------------------------------------------
#                                   SERVER: Puerto y configuración de red local
# ---------------------------------------------------------------------------------------------------------------------
server:
  port: 8081

# ---------------------------------------------------------------------------------------------------------------------
#                               MICROSERVICIO: Direcciones de conexión de servicios externos
# ---------------------------------------------------------------------------------------------------------------------
microservicio:
  cliente:
    url: http://localhost:8083

# ---------------------------------------------------------------------------------------------------------------------
#                                RESILIENCE4J: Configuración del limitador de tiempo de llamadas
# ---------------------------------------------------------------------------------------------------------------------
resilience4j:
  circuitbreaker:
    configs:
      default:
        wait-duration-in-open-state: 5s
  timelimiter:
    configs:
      default:
        timeoutDuration: 30s
    instances:
      default:
        timeoutDuration: 30s

# ---------------------------------------------------------------------------------------------------------------------
#                                   LUKA: Credenciales JWT de seguridad local
# ---------------------------------------------------------------------------------------------------------------------
luka:
  jwt:
    clave-secreta: ${JWT_SECRET_KEY:}
    expiracion-ms: ${JWT_EXPIRATION:86400000}

# ---------------------------------------------------------------------------------------------------------------------
#                                 SPRINGDOC: Habilitación de la consola Swagger OpenAPI
# ---------------------------------------------------------------------------------------------------------------------
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  writer-with-default-pretty-printer: true

# ---------------------------------------------------------------------------------------------------------------------
#                                  LOGGING: Configuración y patrón de trazas log
# ---------------------------------------------------------------------------------------------------------------------
logging:
  level:
    root: INFO
    com:
      usuario: DEBUG
    org:
      springframework:
        security: WARN
        security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
        transaction: INFO
        amqp: WARN
        boot:
          actuate: WARN
      hibernate:
        SQL: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5p [%X{correlationId:-NoID}] - %msg%n"
  file:
    name: logs/microservicio-usuario.log

# ---------------------------------------------------------------------------------------------------------------------
#                                 MANAGEMENT: Redirecciones de Actuator Health
# ---------------------------------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      path-mapping:
        health: health-internal


# Desactivar discovery y eureka
spring:
  cloud:
    discovery:
      enabled: false

management:
  health:
    discovery:
      enabled: false
